### ISSUE TITLE
Research tools for working with patches

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#4704]
## Problem

We don't know what tools exist (besides `quilt`) for working with patches.

## Solution

Research tools, build POCs with each and share findings here.

This will be closed once myself and @code-asher discuss our tool of choice.

### Resources
For using `quilt`:

- http://www.shakthimaan.com/downloads/glv/quilt-tutorial/quilt-doc.pdf
- https://raphaelhertzog.com/2012/08/08/how-to-use-quilt-to-manage-patches-in-debian-packages/
- https://michal.hrusecky.net/2011/10/how-to-create-patches-using-quilt/
- conflict resolution with patch files (tips)
- https://wiki.debian.org/UsingQuilt
- https://linux.die.net/man/1/quilt
- https://raphaelhertzog.com/2012/08/08/how-to-use-quilt-to-manage-patches-in-debian-packages/
- https://perl-team.pages.debian.net/howto/quilt.html

## Related

Part 0/3 of https://github.com/coder/code-server/issues/4687

## TODOS

Create a POC
- [x] create GitHub repo `jsjoeio/quilt-poc`: https://github.com/jsjoeio/quilt-poc
- [x] add a file (use example from `microsoft/vscode`
- [x] find a file we change in our fork `coder/vscode`
- [x] set up `quilt` and create patch
- [x] record video talking through how it works
- [x] summarize and post here

### Notes
`quilt push` to apply patch. `quilt pop` to undo patch.

**Comment by jsjoeio** [comment]
## Summary

`quilt` seems like the best tool available for managing patches. [This blog](https://raphaelhertzog.com/2012/08/08/how-to-use-quilt-to-manage-patches-in-debian-packages/) shows how to perform basic tasks with `quilt`. The [Linux man page](https://linux.die.net/man/1/quilt) has more information as well.  

### Demo

https://user-images.githubusercontent.com/3806031/154367737-ce7a1c10-f7c1-4adb-8a28-2061086f5df4.mov

**Comment by jsjoeio** [comment]
@code-asher assigning to you to watch the demo. Once you take a look, you can post questions/concerns. If we agree on using this tool, you can leave a comment and close this issue.

**Comment by code-asher** [comment]
That was a fantastic demo.  I say we move forward with quilt!
